# application.yml
# 마이바티스 세팅
mybatis:
    type-aliases-package: com.shop.item.model,com.shop.user.model
#    type-handlers-package: com.example.typehandler
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30
    mapper-locations: classpath:mappers/*.xml
    
logging:
  level:
    org.springframework.boot: DEBUG

#DB접속 정보
spring:
  datasource:
    url: jdbc:mysql://itemshop.c3lehcfdsxdf.ap-northeast-2.rds.amazonaws.com/itemshop
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root1234
    